services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - aka_network
      
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: financialDb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - aka_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdocker"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


networks:
  aka_network:
    driver: bridge

volumes:
  mysql_data: